Landing page
googleinterns/step104-2020 pull request #13
Opened 2020-07-06 20:30 UTC by nnenna352

2020-07-07 15:03 UTC, eriyezab requested changes

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    position: relative }
closing brace should go on another line. This goes for the rest as well

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +
could remove these blank lines

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    height: 10em;
indentation should be 2 spaces instead of 4

2020-07-07 15:03 UTC, eriyezab commented on src/main/webapp/landing_page.html
> +    <header>
indentation here should be 2 spaces too

2020-07-07 15:03 UTC, eriyezab commented on src/main/webapp/landing_page.html
> +<body>
this body tag and its closing tag should be indented

2020-07-07 15:03 UTC, eriyezab commented on src/main/webapp/style.css
> +   .search input[type=text], .search button {
looks like it might be indented a bit too much. not in line with the closing brace above it

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    height: 10em;
looks like this file was made before you pulled from mine and you moved a lot of this to the other style.css. All of the suggestions I made on this file applies to that one :) But I think that you should delete this file along with everything that was in the Dashboard directory you created. Make sure you copy everything you need before deleting though

2020-07-07 15:03 UTC, eriyezab commented on src/main/webapp/style.css
> +p {font-size:50px;}
Even though these can fit in one line I think they should follow the same format where the code is on a separate line

2020-07-07 15:03 UTC, eriyezab commented on src/main/webapp/style.css
> +h1{font-size:70px;}
ditto

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    overflow:hidden;
add space after colon

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    white-space:nowrap;
ditto

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    0%{
space before brace

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +        width:0ch;
space after colon

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +    100%{
space before brace

2020-07-07 15:03 UTC, eriyezab commented on Dashboard/src/main/webapp/style.css
> +        width:30ch;
space after colon

2020-07-07 15:03 UTC, eriyezab commented on src/main/webapp/style.css
> +.landing {
same comments from the first css file up to line 37

2020-07-08 20:25 UTC, TMazenge commented on Dashboard/src/main/webapp/style.css
> +}
Add blank line at the end.

2020-07-08 20:25 UTC, TMazenge commented on src/main/webapp/style.css
> +}
add line here as well.

2020-07-13 16:46 UTC, closed without merging