Release style
googleinterns/step104-2020 pull request #21
Opened 2020-07-09 19:13 UTC by TMazenge

Added common styling to the Release History Page.

2020-07-10 15:05 UTC, eriyezab requested changes
nit: indentation should be 2 spaces not 4 https://google.github.io/styleguide/htmlcssguide.html#Indentation

2020-07-10 15:05 UTC, eriyezab commented on src/main/webapp/release_history.html
> +                    <th><a href="https://github.com/FirebasePrivate/firebase-android-sdk/tree/M72">M72</th>
This is my bad I didn't see this when I committed this part but I forgot to put a closing \</a> tag in all of these.

2020-07-10 15:05 UTC, eriyezab commented on src/main/webapp/release_history.html
> +                    <tr>
all th tags between tr tags should be indented

2020-07-10 15:05 UTC, eriyezab commented on src/main/webapp/release_history.html
> +                <table class="table table-bordered justify-content-center" style="border: 1px solid #ddd !important;">
ideally styling should strictly be in css file. refer to https://google.github.io/styleguide/htmlcssguide.html#Separation_of_Concerns

2020-07-13 16:25 UTC, ankitaj224 approved these changes
Mostly LGTM. I am approving it given we will change the dummy data to read from backend.

Thanks

2020-07-14 15:39 UTC, eriyezab approved these changes

2020-07-14 19:14 UTC, merged