Add release
googleinterns/step104-2020 pull request #26
Opened 2020-07-13 05:53 UTC by nnenna352

2020-07-14 00:03 UTC, shrutip90 requested changes

2020-07-14 00:03 UTC, shrutip90 commented on Dashboard/src/main/webapp/style.css
> +}
Please take care of the warning.

2020-07-14 00:03 UTC, shrutip90 commented on Dashboard/src/main/webapp/style.css
> +
Do you need double blank lines here?

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +</html>
Warning.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +                        <p>Launch Deadline:</p>
-> Launchcal Deadline

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +                        <p>Automatically Send Out Ros at Cold Freeze</p>
what's 'Ros'?

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/auth.html
> +<html>
Diff against the branch with the auth changes, so that this does not appear in this PR. If you have merged the auth PR already, you can also rebase this PR to pull those changes.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/css/style.css
> +
Too many blank lines.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/css/style.css
> +}*/
Please do not add commented code blocks. It is a better practice to just rewrite them later if required.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/css/style.css
> +
Please keep the spacing consistent throughout the file. Check the style guide and add either one or two blank lines between all the code blocks.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/css/style.css
> +/* Wizard Section*/
Add spaces at the end of comment.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/css/style.css
> +/*Product Release*/
Add spaces before and after the comment. Please check the other comments in the file and make sure all of them have consistent styling.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/landing_page.html
> +<!DOCTYPE html>
Looks like these are from another PR as well. Not reviewing them here.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/product_release.html
> +<html lang="en">
Looks like these are from another PR as well. Not reviewing them here.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/style.css
> +}
Warning.

2020-07-14 00:03 UTC, shrutip90 commented on target/maven-archiver/pom.properties
>  artifactId=sdktiktok
Change name.

2020-07-14 00:03 UTC, shrutip90 commented on src/main/webapp/style.css
> +.favorite {
Looks like these are from another PR as well. Not reviewing them here.

2020-07-14 00:05 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +      <title>Product Release</title>
-> New Release

2020-07-14 00:05 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +            <h1>Product Release</h1>
New Release

2020-07-16 04:51 UTC, nnenna352 commented on src/main/webapp/add_release.html
> +                        <p>Automatically Send Out Ros at Cold Freeze</p>
That's what I saw on the figma I am not sure

2020-07-16 04:51 UTC, nnenna352 commented on Dashboard/src/main/webapp/style.css
> +
I deleted this file. It is a duplicate.

2020-07-16 16:50 UTC, shrutip90 requested changes

2020-07-16 16:50 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +                        <p>Automatically Send Out Ros at Cold Freeze</p>
Checked the prototype..it is RCs, meaning Release Candidates. Please update and also make this a Yes/No question field.

2020-07-16 16:50 UTC, shrutip90 commented on src/main/webapp/add_release.html
> +                        <p>Launch:</p>
All the fields in this page are supposed to allow inputs from user. But it looks like you have just added the labels, can you please check.

2020-07-19 20:56 UTC, merged