Release history html prototype
googleinterns/step104-2020 pull request #4
Opened 2020-07-02 18:22 UTC by eriyezab

Closes #2.
Created the html skeleton with example data for the release history page
Initializes front end directory structure.
Adds some dependencies to pom.xml.

2020-07-06 13:55 UTC, TMazenge approved these changes
LGTM

2020-07-08 19:43 UTC, ankitaj224 requested changes
I am unsure if you want to check in files under target/. I presume not . PTAL.

2020-07-08 19:43 UTC, ankitaj224 commented on pom.xml
> +  <groupId>com.google.capstone</groupId>
Have a generic group id specific to Firebase dashboard

2020-07-08 19:43 UTC, ankitaj224 commented on pom.xml
> +    </dependency>
new line between dependencies.

2020-07-08 19:43 UTC, ankitaj224 commented on target/sdktiktok-1/release_history.html
> +<!DOCTYPE html>
Do you want to check this in?

2020-07-08 19:46 UTC, ankitaj224 reviewed
Add a directory for images/

2020-07-09 22:47 UTC, ankitaj224 approved these changes

2020-07-09 22:47 UTC, ankitaj224 commented on src/main/webapp/enroll.html
> +        <form action="/action_page.php" class="text-center">
php?

2020-07-09 23:05 UTC, merged